version: '3'
services:
  trading-api:
    build:
      context: https://github.com/M7011E-django-unchained/trading_api.git
    image: m7011e-django-unchained/trading_api
    volumes:
      - ./db.sqlite3:/usr/src/app/db.sqlite3
    container_name: trading-api-container
    restart: always
    ports:
      - 8000:8000

  bidding_system:
    image: m7011e-django-unchained/bidding_system
    container_name: bidding-system-container
    restart: always
    build: 
      context: https://github.com/M7011E-django-unchained/bidding-system.git
    ports:
      - 5000:5000
    command: bash -c "chmod +x /usr/src/bidding-system/start.sh && /usr/src/bidding-system/start.sh"
    env_file: .env
